# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math
import os

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _sdpa_math_kernel(
    Q,
    K,
    V,
    ATTN_MASK,
    Out,
    Weights,
    sm_scale,
    stride_qb,
    stride_qh,
    stride_qm,
    stride_qk,
    stride_kb,
    stride_kh,
    stride_kn,
    stride_kk,
    stride_vb,
    stride_vh,
    stride_vn,
    stride_vk,
    stride_mb,
    stride_mh,
    stride_mm,
    stride_mn,
    stride_ob,
    stride_oh,
    stride_om,
    stride_ok,
    stride_wb,
    stride_wh,
    stride_wm,
    stride_wn,
    Q_CTX,
    KV_CTX,
    HEADS: tl.constexpr,
    HEAD_DIM: tl.constexpr,
    BLOCK_D: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    IS_CAUSAL: tl.constexpr,
    HAS_ATTN_MASK: tl.constexpr,
):
    start_m = tl.program_id(0)
    off_z = tl.program_id(1)
    off_b = off_z // HEADS
    off_h = off_z - off_b * HEADS

    q_base = Q + off_b * stride_qb + off_h * stride_qh
    k_base = K + off_b * stride_kb + off_h * stride_kh
    v_base = V + off_b * stride_vb + off_h * stride_vh
    o_base = Out + off_b * stride_ob + off_h * stride_oh
    w_base = Weights + off_b * stride_wb + off_h * stride_wh

    offs_m = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)
    d_mask = offs_d < HEAD_DIM

    q_mask = offs_m < Q_CTX
    q_ptrs = q_base + offs_m[:, None] * stride_qm + offs_d[None, :] * stride_qk
    # Keep Q/K/V in their native dtype so tl.dot uses tensor cores; only the
    # softmax statistics and accumulators run in fp32.
    query = tl.load(q_ptrs, mask=q_mask[:, None] & d_mask[None, :], other=0.0)

    LOG2E: tl.constexpr = 1.4426950408889634

    m_i = tl.full([BLOCK_M], -float("inf"), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    if IS_CAUSAL:
        # Top-left causal masking: query row i attends to key j when j <= i,
        # matching torch's tril(diagonal=0) in the math reference.
        hi = tl.minimum((start_m + 1) * BLOCK_M, KV_CTX)
    else:
        hi = KV_CTX

    # Pass 1: online softmax to compute row max (m_i), row sum (l_i) and the
    # unnormalized output accumulator in a single streaming loop.
    for start_n in range(0, hi, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        kv_mask = offs_n < KV_CTX

        k_ptrs = k_base + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kk
        key = tl.load(k_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)

        qk = (
            tl.dot(query, tl.trans(key), input_precision="ieee").to(tl.float32)
            * sm_scale
        )

        if HAS_ATTN_MASK:
            m_ptrs = (
                ATTN_MASK
                + off_b * stride_mb
                + off_h * stride_mh
                + offs_m[:, None] * stride_mm
                + offs_n[None, :] * stride_mn
            )
            load_mask = q_mask[:, None] & kv_mask[None, :]
            add_mask = tl.load(m_ptrs, mask=load_mask, other=0.0).to(tl.float32)
            qk += add_mask

        qk = tl.where(kv_mask[None, :], qk, -float("inf"))

        if IS_CAUSAL:
            causal = offs_m[:, None] >= offs_n[None, :]
            qk = tl.where(causal, qk, -float("inf"))

        m_ij = tl.maximum(m_i, tl.max(qk, 1))
        m_ij_safe = tl.where(m_ij == -float("inf"), 0.0, m_ij)
        p = tl.exp2((qk - m_ij_safe[:, None]) * LOG2E)
        alpha = tl.exp2((m_i - m_ij_safe) * LOG2E)
        l_i = l_i * alpha + tl.sum(p, 1)

        v_ptrs = v_base + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vk
        value = tl.load(v_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)

        acc = acc * alpha[:, None]
        acc += tl.dot(
            p.to(value.dtype), value, input_precision="ieee"
        ).to(tl.float32)
        m_i = m_ij_safe

    l_safe = tl.where(l_i == 0.0, 1.0, l_i)
    acc = acc / l_safe[:, None]

    o_ptrs = o_base + offs_m[:, None] * stride_om + offs_d[None, :] * stride_ok
    tl.store(
        o_ptrs, acc.to(Out.dtype.element_ty), mask=q_mask[:, None] & d_mask[None, :]
    )

    # Pass 2: recompute normalized probabilities with the finalized m_i / l_i
    # and materialize the full (Q_CTX, KV_CTX) attention weight matrix.
    for start_n in range(0, KV_CTX, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        kv_mask = offs_n < KV_CTX

        k_ptrs = k_base + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kk
        key = tl.load(k_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)
        qk = (
            tl.dot(query, tl.trans(key), input_precision="ieee").to(tl.float32)
            * sm_scale
        )

        if HAS_ATTN_MASK:
            m_ptrs = (
                ATTN_MASK
                + off_b * stride_mb
                + off_h * stride_mh
                + offs_m[:, None] * stride_mm
                + offs_n[None, :] * stride_mn
            )
            load_mask = q_mask[:, None] & kv_mask[None, :]
            add_mask = tl.load(m_ptrs, mask=load_mask, other=0.0).to(tl.float32)
            qk += add_mask

        keep = kv_mask[None, :]
        if IS_CAUSAL:
            causal = offs_m[:, None] >= offs_n[None, :]
            keep = keep & causal

        p = tl.exp2((qk - m_i[:, None]) * LOG2E)
        p = tl.where(keep, p, 0.0) / l_safe[:, None]

        w_ptrs = w_base + offs_m[:, None] * stride_wm + offs_n[None, :] * stride_wn
        store_mask = q_mask[:, None] & kv_mask[None, :]
        tl.store(w_ptrs, p.to(Weights.dtype.element_ty), mask=store_mask)


def _scaled_dot_product_attention_math_forward(
    query,
    key,
    value,
    attn_mask=None,
    dropout_p=0.0,
    is_causal=False,
    scale=None,
):
    """Computes scaled dot-product attention with an explicit softmax and
    returns both the attention output and the full attention weight matrix."""
    logger.debug("GEMS _SCALED_DOT_PRODUCT_ATTENTION_MATH")

    assert dropout_p == 0.0, "dropout_p != 0.0 is not supported"
    assert query.dim() >= 3, (
        "expected tensors shaped (..., heads, seq_len, head_dim)"
    )
    assert query.dim() == key.dim() == value.dim(), (
        "query, key and value must have the same rank"
    )

    batch_shape = query.shape[:-3]
    heads, q_seq_len, head_dim = query.shape[-3:]
    batch = math.prod(batch_shape)
    kv_seq_len = key.shape[-2]

    assert key.shape[:-3] == batch_shape and value.shape[:-3] == batch_shape, (
        "query, key and value must have the same batch dimensions"
    )
    assert key.shape[-3] == heads and value.shape[-3] == heads, (
        "query, key and value must have the same number of heads"
    )
    assert key.shape[-1] == head_dim and value.shape[-1] == head_dim, (
        "query, key and value must have the same head dimension"
    )
    assert value.shape[-2] == kv_seq_len, (
        "key and value must have the same sequence length"
    )

    if scale is None:
        scale = 1.0 / math.sqrt(head_dim)

    out = torch.empty_like(query)
    weights = torch.empty(
        (*batch_shape, heads, q_seq_len, kv_seq_len),
        dtype=query.dtype,
        device=query.device,
    )

    has_attn_mask = attn_mask is not None
    if has_attn_mask:
        assert attn_mask.dtype != torch.bool, "boolean attn_mask is not supported"
        attn_mask = attn_mask.expand(
            *batch_shape, heads, q_seq_len, kv_seq_len
        )

    # Rank-3/4 attention is the common model path. Keep its original batch/head
    # strides so sliced K/V and permuted masks do not need materialization.
    direct_strided = query.dim() in (3, 4)
    if direct_strided:
        q_launch, k_launch, v_launch = query, key, value
        o_launch, w_launch = out, weights
        mask_launch = attn_mask if has_attn_mask else query
        if query.dim() == 4:
            q_strides = query.stride()
            k_strides = key.stride()
            v_strides = value.stride()
            o_strides = out.stride()
            w_strides = weights.stride()
            m_strides = attn_mask.stride() if has_attn_mask else (0, 0, 0, 0)
        else:
            q_strides = (0, *query.stride())
            k_strides = (0, *key.stride())
            v_strides = (0, *value.stride())
            o_strides = (0, *out.stride())
            w_strides = (0, *weights.stride())
            m_strides = (
                (0, *attn_mask.stride()) if has_attn_mask else (0, 0, 0, 0)
            )
        launch_heads = heads
        grid_z = batch * heads
    else:
        # Preserve the established arbitrary-batch-rank path by folding a
        # contiguous copy into one leading dimension.
        q_launch = query.contiguous().reshape(batch * heads, q_seq_len, head_dim)
        k_launch = key.contiguous().reshape(batch * heads, kv_seq_len, head_dim)
        v_launch = value.contiguous().reshape(batch * heads, kv_seq_len, head_dim)
        o_launch = out.reshape(batch * heads, q_seq_len, head_dim)
        w_launch = weights.reshape(batch * heads, q_seq_len, kv_seq_len)
        q_strides = (0, *q_launch.stride())
        k_strides = (0, *k_launch.stride())
        v_strides = (0, *v_launch.stride())
        o_strides = (0, *o_launch.stride())
        w_strides = (0, *w_launch.stride())
        if has_attn_mask:
            mask_launch = attn_mask.contiguous().reshape(
                batch * heads, q_seq_len, kv_seq_len
            )
            m_strides = (0, *mask_launch.stride())
        else:
            mask_launch = q_launch
            m_strides = (0, 0, 0, 0)
        launch_heads = batch * heads
        grid_z = batch * heads

    # BLOCK_M/BLOCK_N = 32 to stay within shared memory limits (166KB on T4/A10).
    # The two-pass algorithm (forward + materialize weights) requires ~2x memory
    # vs. a single-pass kernel, so smaller blocks are necessary.
    # Diagnostic-only override used for same-process A/B measurements; the
    # production path leaves it unset and uses the measured default below.
    block_override = os.environ.get("FLAG_GEMS_PPU_SDPA_BLOCK", "")
    if query.dim() == 4 and (q_seq_len, kv_seq_len, head_dim) == (32, 128, 32):
        # The traced Protenix local-attention shape is small enough for a full
        # 32-row query tile.  It removes one query-grid program while keeping
        # the 32-column reduction tile within the PPU register/shared-memory
        # budget; measured on PPU this is faster than the former 16x64 split.
        if block_override:
            try:
                BLOCK_M, BLOCK_N = (int(x) for x in block_override.split("x", 1))
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    "FLAG_GEMS_PPU_SDPA_BLOCK must be '<BLOCK_M>x<BLOCK_N>'"
                ) from exc
        else:
            BLOCK_M = 32
            BLOCK_N = 32
    else:
        BLOCK_M = 32
        BLOCK_N = 32

    # Launch parameters are intentionally opt-in diagnostics.  They allow a
    # same-source A/B on PPU without changing the NVIDIA/default dispatch.
    # The values are compile-time launch metadata, not numerical shortcuts.
    launch_options = {}
    for env_name, option_name in (
        ("FLAG_GEMS_PPU_SDPA_NUM_WARPS", "num_warps"),
        ("FLAG_GEMS_PPU_SDPA_NUM_STAGES", "num_stages"),
    ):
        value = os.environ.get(env_name, "")
        if value:
            try:
                parsed = int(value)
            except ValueError as exc:
                raise ValueError(f"{env_name} must be a positive integer") from exc
            if parsed <= 0:
                raise ValueError(f"{env_name} must be a positive integer")
            launch_options[option_name] = parsed
    # tl.arange over the head dim requires a power-of-2 span; pad and mask.
    BLOCK_D = triton.next_power_of_2(head_dim)

    grid = (triton.cdiv(q_seq_len, BLOCK_M), grid_z)

    with torch_device_fn.device(query.device):
        _sdpa_math_kernel[grid](
            q_launch,
            k_launch,
            v_launch,
            mask_launch,
            o_launch,
            w_launch,
            scale,
            *q_strides,
            *k_strides,
            *v_strides,
            *m_strides,
            *o_strides,
            *w_strides,
            q_seq_len,
            kv_seq_len,
            HEADS=launch_heads,
            HEAD_DIM=head_dim,
            BLOCK_D=BLOCK_D,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            IS_CAUSAL=is_causal,
            HAS_ATTN_MASK=has_attn_mask,
            **launch_options,
        )

    return out, weights


class _ScaledDotProductAttentionMathAutograd(torch.autograd.Function):
    """Autograd for the FlagGems SDPA math implementation."""

    @staticmethod
    def forward(
        ctx,
        query,
        key,
        value,
        attn_mask=None,
        dropout_p=0.0,
        is_causal=False,
        scale=None,
    ):
        out, weights = _scaled_dot_product_attention_math_forward(
            query,
            key,
            value,
            attn_mask=attn_mask,
            dropout_p=dropout_p,
            is_causal=is_causal,
            scale=scale,
        )
        ctx.scale = (
            float(scale)
            if scale is not None
            else 1.0 / math.sqrt(query.shape[-1])
        )
        ctx.mask_shape = tuple(attn_mask.shape) if attn_mask is not None else None
        ctx.mask_requires_grad = bool(
            attn_mask is not None and attn_mask.requires_grad
        )
        ctx.save_for_backward(query, key, value, weights)
        return out, weights

    @staticmethod
    def backward(ctx, grad_out, grad_weights):
        query, key, value, weights = ctx.saved_tensors

        if grad_out is None:
            grad_out = torch.zeros_like(query)

        grad_value = torch.matmul(weights.transpose(-2, -1), grad_out)
        grad_probability = torch.matmul(grad_out, value.transpose(-2, -1))
        if grad_weights is not None:
            grad_probability = grad_probability + grad_weights

        grad_score = weights * (
            grad_probability
            - (grad_probability * weights).sum(dim=-1, keepdim=True)
        )
        grad_query = torch.matmul(grad_score, key) * ctx.scale
        grad_key = torch.matmul(grad_score.transpose(-2, -1), query) * ctx.scale

        grad_mask = None
        if ctx.mask_requires_grad:
            grad_mask = grad_score.sum_to_size(ctx.mask_shape)

        return grad_query, grad_key, grad_value, grad_mask, None, None, None


def _scaled_dot_product_attention_math(
    query,
    key,
    value,
    attn_mask=None,
    dropout_p=0.0,
    is_causal=False,
    scale=None,
):
    return _ScaledDotProductAttentionMathAutograd.apply(
        query,
        key,
        value,
        attn_mask,
        dropout_p,
        is_causal,
        scale,
    )
