# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import os
from contextlib import nullcontext

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)


@triton.jit
def _fma_rn_f32(a, b, acc):
    """Perform one explicitly ordered FP32 round-to-nearest FMA."""
    return tl.inline_asm_elementwise(
        asm="fma.rn.f32 $0, $1, $2, $3;",
        constraints="=f,f,f,f",
        args=[a, b, acc],
        dtype=tl.float32,
        is_pure=True,
        pack=1,
    )


def _linear_config_signature(config):
    meta = config.all_kwargs()
    return (
        int(meta["BLOCK_SIZE_M"]),
        int(meta["BLOCK_SIZE_N"]),
        int(meta["BLOCK_SIZE_K"]),
        int(meta["num_warps"]),
        int(meta["num_stages"]),
    )


def _prune_thead_fp32_linear_configs(configs, nargs, **kwargs):
    """Select the measured PPU schedule without per-shape autotuning."""
    input_tensor = nargs.get("input_ptr")
    if (
        runtime.device.vendor_name != "thead"
        or getattr(input_tensor, "dtype", None) != torch.float32
    ):
        return configs
    # The large FP32 projections dominate the Protenix trace.  On the current
    # PPU compiler, real M>=100k/K in {256,1024}/N>=256 shapes consistently
    # prefer M64,N64,K32 with three stages; keeping this guard shape-specific
    # avoids applying the large-matrix choice to narrow or tail projections.
    m = int(nargs["M"])
    n = int(nargs["N"])
    k = int(nargs["K"])
    # Keep an explicit A/B switch for controlled end-to-end measurements.
    # ``legacy`` reproduces the previous production heuristic; ``candidate``
    # forces the newly measured M64/N64/K32/W4/S3 schedule.  With no override,
    # use the shape-aware candidate only for the large projections below.
    schedule_override = os.getenv("FLAG_GEMS_PPU_LINEAR_SCHEDULE", "").strip().lower()
    if schedule_override in {"legacy", "m128n32_or_m128n64k32w4s4"}:
        target = (128, 32, 32, 4, 4) if n <= 32 else (128, 64, 32, 4, 4)
    elif schedule_override in {"candidate", "m64n64k32w4s3"}:
        target = (64, 64, 32, 4, 3)
    elif m >= 100_000 and n >= 256 and k in (256, 1024):
        target = (64, 64, 32, 4, 3)
    else:
        target = (128, 32, 32, 4, 4) if n <= 32 else (128, 64, 32, 4, 4)
    selected = [config for config in configs if _linear_config_signature(config) == target]
    return selected if len(selected) == 1 else configs


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("linear"),
    key=["M", "N", "K"],
    strategy=["align32", "align32", "align32"],
    prune_configs_by={"early_config_prune": _prune_thead_fp32_linear_configs},
    warmup=5,
    rep=10,
)
@triton.jit
def linear_kernel(
    input_ptr,
    weight_ptr,
    bias_ptr,
    output_ptr,
    M,
    N,
    K,
    stride_im,
    stride_ik,
    stride_wn,
    stride_wk,
    stride_om,
    stride_on,
    stride_bn,
    # Bias is present or not
    BIAS: tl.constexpr,
    ALLOW_TF32: tl.constexpr,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
):
    """
    Linear kernel: y = x @ W^T + b
    - input: (M, K) where M is batch size (flattened), K is in_features
    - weight: (N, K) where N is out_features
    - bias: (N,) optional
    - output: (M, N)
    """
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_n = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    input_ptrs = input_ptr + (offs_m[:, None] * stride_im + offs_k[None, :] * stride_ik)

    weight_ptrs = weight_ptr + (
        offs_k[:, None] * stride_wk + offs_n[None, :] * stride_wn
    )

    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    for k in range(0, tl.cdiv(K, BLOCK_SIZE_K)):
        # Load input block
        input_mask_m = offs_m < M
        input_mask_k = offs_k < (K - k * BLOCK_SIZE_K)
        input_mask = input_mask_m[:, None] & input_mask_k[None, :]

        a = tl.load(input_ptrs, mask=input_mask, other=0.0)

        # Load weight block
        weight_mask_k = offs_k < (K - k * BLOCK_SIZE_K)
        weight_mask_n = offs_n < N
        weight_mask = weight_mask_k[:, None] & weight_mask_n[None, :]

        b = tl.load(weight_ptrs, mask=weight_mask, other=0.0)

        # Compute dot product
        accumulator += tl.dot(a, b, allow_tf32=ALLOW_TF32)

        # Move to next block
        input_ptrs += BLOCK_SIZE_K * stride_ik
        weight_ptrs += BLOCK_SIZE_K * stride_wk

    # Compute output offset
    offs_om = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_on = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    output_ptrs = output_ptr + (
        offs_om[:, None] * stride_om + offs_on[None, :] * stride_on
    )

    output_mask_m = offs_m < M
    output_mask_n = offs_n < N
    output_mask = output_mask_m[:, None] & output_mask_n[None, :]

    # Add bias if present
    if BIAS:
        bias_ptrs = bias_ptr + offs_on
        bias = tl.load(bias_ptrs, mask=output_mask_n, other=0.0)
        accumulator = accumulator + bias

    # Store result
    output = accumulator.to(output_ptr.dtype.element_ty)
    tl.store(output_ptrs, output, mask=output_mask)


@triton.jit
def linear_kernel_smallk_rn(
    input_ptr,
    weight_ptr,
    bias_ptr,
    output_ptr,
    M,
    N,
    K: tl.constexpr,
    stride_im,
    stride_ik,
    stride_wn,
    stride_wk,
    stride_om,
    stride_on,
    stride_bn,
    BIAS: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Fixed-order FP32 FMA path for the tiny-K projection family.

    The path is deliberately selected only by the Python dispatch guard below.
    It makes the accumulation order explicit for K=1..4, which is the family
    where the PPU result can otherwise differ from the H100 native reference.
    """
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    valid_m = offs_m < M
    valid_n = offs_n < N
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for k in range(K):
        a = tl.load(
            input_ptr + offs_m * stride_im + k * stride_ik,
            mask=valid_m,
            other=0.0,
        )
        b = tl.load(
            weight_ptr + k * stride_wk + offs_n * stride_wn,
            mask=valid_n,
            other=0.0,
        )
        acc = _fma_rn_f32(
            tl.broadcast_to(a[:, None], (BLOCK_M, BLOCK_N)),
            tl.broadcast_to(b[None, :], (BLOCK_M, BLOCK_N)),
            acc,
        )
    if BIAS:
        bias = tl.load(bias_ptr + offs_n * stride_bn, mask=valid_n, other=0.0)
        acc += bias[None, :]
    output_ptrs = output_ptr + offs_m[:, None] * stride_om + offs_n[None, :] * stride_on
    tl.store(output_ptrs, acc.to(output_ptr.dtype.element_ty), mask=valid_m[:, None] & valid_n[None, :])


def linear(input, weight, bias=None):
    """
    Applies a linear transformation to the incoming data: y = xA^T + b

    Args:
        input: Input tensor of shape (*, in_features) where * means any number of
               additional dimensions, including none.
        weight: Weight tensor of shape (out_features, in_features)
        bias: Bias tensor of shape (out_features), optional

    Returns:
        Output tensor of shape (*, out_features)
    """
    logger.debug("GEMS LINEAR")

    input_dim = input.dim()
    if input_dim == 1:
        # Single 1D input: treat as (1, in_features)
        input = input.unsqueeze(0)
        single_1d = True
    else:
        single_1d = False

    # Flatten batch dimensions: (*, in_features) -> (batch, in_features)
    batch_dims = input.shape[:-1]
    batch_size = 1
    for dim in batch_dims:
        batch_size *= dim
    M = batch_size
    K = input.shape[-1]  # in_features
    N = weight.shape[0]  # out_features
    allow_tf32 = (
        os.getenv("FLAG_GEMS_PPU_FAST_FP32", "0") == "1"
        and runtime.device.vendor_name == "thead"
        and input.dtype == torch.float32
        and M >= 32768
        and K >= 256
        and N >= 256
    )
    # The reduction-major weight layout was validated on all nine inference
    # models with bitwise-identical predictions and an aggregate 18.5% PPU
    # speedup.  Enable it by default for large, grad-free PPU projections;
    # ``FLAG_GEMS_PPU_PACKED_LINEAR=0`` keeps an explicit rollback switch.
    pack_weight = (
        os.getenv(
            "FLAG_GEMS_PPU_PACKED_LINEAR",
            "1" if runtime.device.vendor_name == "thead" else "0",
        )
        == "1"
        and runtime.device.vendor_name == "thead"
        and input.dtype == torch.float32
        and not torch.is_grad_enabled()
        and M >= 32768
    )

    # Flatten input: (*, K) -> (M, K)
    input_flat = input.view(M, K)

    # PPU reads the reduction-major (K, N) layout much more efficiently.
    if pack_weight:
        cache_key = (
            weight._version,
            weight.data_ptr(),
            tuple(weight.shape),
            tuple(weight.stride()),
        )
        cached = getattr(weight, "_flag_gems_ppu_packed_linear", None)
        if cached is None or cached[0] != cache_key:
            cached = (cache_key, weight.transpose(0, 1).contiguous())
            weight._flag_gems_ppu_packed_linear = cached
        weight_for_kernel = cached[1]
        weight_stride_n = weight_for_kernel.stride(1)
        weight_stride_k = weight_for_kernel.stride(0)
    else:
        weight_for_kernel = weight.contiguous()
        weight_stride_n = weight_for_kernel.stride(0)
        weight_stride_k = weight_for_kernel.stride(1)

    # Allocate output
    output = torch.empty((M, N), device=input.device, dtype=input.dtype)

    # Launch kernel
    grid = lambda META: (
        triton.cdiv(M, META["BLOCK_SIZE_M"]),
        triton.cdiv(N, META["BLOCK_SIZE_N"]),
    )

    # An optional diagnostic mode bypasses the persistent shape->config DB.
    # Normal A/B runs should instead use separate FLAGGEMS_CACHE_DIR values:
    # that keeps one tuning result per arm without retuning every invocation.
    schedule_override = os.getenv("FLAG_GEMS_PPU_LINEAR_SCHEDULE", "").strip().lower()
    force_policy = os.getenv("FLAG_GEMS_PPU_LINEAR_FORCE_POLICY", "0") == "1"
    smallk_rn = (
        os.getenv("FLAG_GEMS_PPU_LINEAR_SMALLK_RN", "0") == "1"
        and runtime.device.vendor_name == "thead"
        and input.dtype == torch.float32
        and not allow_tf32
        and not pack_weight
        and 1 <= K <= 4
    )
    run_context = (
        linear_kernel.fn.use_run_mode("force_policy")
        if force_policy
        and schedule_override in {"legacy", "m128n32_or_m128n64k32w4s4", "candidate", "m64n64k32w4s3"}
        else nullcontext()
    )
    with torch_device_fn.device(input.device), run_context:
        if smallk_rn:
            linear_kernel_smallk_rn[(triton.cdiv(M, 64), triton.cdiv(N, 128))](
                input_flat,
                weight_for_kernel,
                bias if bias is not None else weight_for_kernel,
                output,
                M,
                N,
                K=K,
                stride_im=input_flat.stride(0),
                stride_ik=input_flat.stride(1),
                stride_wn=weight_stride_n,
                stride_wk=weight_stride_k,
                stride_om=output.stride(0),
                stride_on=output.stride(1),
                stride_bn=bias.stride(0) if bias is not None else 0,
                BIAS=bias is not None,
                BLOCK_M=64,
                BLOCK_N=128,
            )
        else:
            linear_kernel[grid](
                input_flat,
                weight_for_kernel,
                bias if bias is not None else weight_for_kernel,
                output,
                M,
                N,
                K,
                input_flat.stride(0),
                input_flat.stride(1),
                weight_stride_n,
                weight_stride_k,
                output.stride(0),
                output.stride(1),
                bias.stride(0) if bias is not None else 0,
                BIAS=bias is not None,
                ALLOW_TF32=allow_tf32,
            )

    # Reshape output: (M, N) -> (*, N)
    output = output.view(*batch_dims, N)

    # If original input was 1D, squeeze the batch dim
    if single_1d:
        output = output.squeeze(0)

    return output
